### ISSUE TITLE
Authentication for REST Api?

### ISSUE THREAD

**Issue by tejinderss** [vmwaresamples/vra-api-samples-for-postman#4]
I have chosen vra as authentication for vro. Vra is using vidm (workspace one) as authentication provider. The version is 7.3. Whats the best way to authenticate for the API? Should I use http bearer token at /identitity/api/tokens or SAAS/t/vsphere.local/auth/oauthtoken password grant type token? Or is there any other best way out there. I could not find documentation suggesting that, thats why creating a ticket here. Thanks

**Comment by sbhandari** [comment]
I am trying to understand it. You want to get authorization token to access vRO API, is that right?

`https://{{va-fqdn}}/identitity/api/tokens` gives you Cafe token.
`https://{va-fqdn}}/SAAS/t/vsphere.local/auth/oauthtoken` gives you vIDM token.

**Comment by tejinderss** [comment]
Yes I want to access vro using vidm but both of these ways are not working.
I get login page back if I try to access vro api with bearer authorization
token

**Comment by sbhandari** [comment]
okay I just tried it and seems to work. I posted a sample for you

Please import the collection in your postman client. See if this works for you.

https://github.com/vmwaresamples/vra-api-samples-for-postman/tree/master/vRO

**Comment by tejinderss** [comment]
This uses va-fqdn for vro and vro. Our use case is different, vra and vro
are on separate hosts and vro has authentication provider set to vrealize
automation. Both vra and vro are on 7.3. guess vra is using vidm workspace
one login.
Thanks

**Comment by sbhandari** [comment]
okay. I tried it in this setup. 

vRA as auth provider.

`Default tenant: {{tenant}}`
`Admin Group: one of the group I can see in Directory Groups`

Now I used the same call 

`POST https://{{vra-va-fqdn}}/SAAS/t/{{tenant}}/auth/oauthtoken?grant_type=password`

In the request body (x-www-form-urlencoded)

```
username: {{tenant-user-who-is-part-of-directory-groups}}
password: {{password}}
client_id: {{grep-command-output}}
domain: {{domain-of-tenant-user-selected-above}}
```
I get a token and I use that token to do GET /vco/api/workflows

**Comment by tejinderss** [comment]
Sorry I was trying to access the controlcenter and there is open bug for vmware for this.

**Comment by sbhandari** [comment]
Closing this.
